### ISSUE TITLE
Tolerations parameter type is invalid

### ISSUE THREAD

**Issue by mazay** [giantswarm/starboard-exporter#157]
With added schema validation deployment fails when having tolerations configured.

Used config:

```yaml
...
tolerations:
  # allow scheduling on any node
  - operator: Exists
...
``` 

Error message:

```bash
Helm upgrade failed: values don't meet the specifications of the schema(s) in the following chart(s):
starboard-exporter:
- tolerations: Invalid type. Expected: object, given: array
```
