### ISSUE TITLE
starboard-exporter crashing because of missing permisisons

### ISSUE THREAD

**Issue by sfhl** [giantswarm/starboard-exporter#191]
Hi there,
using the helm template, starboard exporter crashes because of the following error

```
E0213 12:21:46.781018       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: endpoints "starboard-exporter" is forbidden: User "system:serviceaccount:security:starboard-exporter" cannot list resource "endpoints" in API group "" in the namespace "security"
```
I guess this  may be easily fixed by moving the following code from `Role` `starboard-exporter-psp` to `ClusterRole` `starboard-exporter` (for example).

```
...
    - apiGroups:       
        - ""           
      resources:       
        - endpoints    
      verbs:           
        - get          
        - list         
        - watch        
...
```
