### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by albertschwarzkopf** [giantswarm/starboard-exporter#71]
Hi, I like your exporter. Could you build and provide images for ARM too, please?

Or enable affinities via values.yaml? 

E.g:

```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
```

We have clusters with arm-based worker nodes and amd-based worker nodes.
